name: IAFurnitureBreakRestricter
version: '${version}'
description: "ItemsAdder Furniture Protection is a lightweight addon for the ItemsAdder Minecraft plugin that restricts breaking of custom furniture items. It's specifically designed for minigame servers (especially BedWars, SkyWars, and similar games) where traditional protection plugins like WorldGuard cannot be effectively used without causing gameplay issues."
author: alex2276564
main: uz.alex2276564.iafurniturebreakrestricter.IAFurnitureBreakRestricter
api-version: '1.16'
website: https://github.com/alex2276564/IAFurnitureBreakRestricter
depend:
  - ItemsAdder
permissions:
  ia.furniture.break:
    description: Allows breaking ItemsAdder furniture
    default: op