name: Bug Report
description: Report a bug in ItemsAdder Furniture Protection
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report! Please provide as much information as possible."

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      placeholder: "e.g., 1.16.5"
    validations:
      required: true

  - type: input
    id: server-software
    attributes:
      label: Server Software
      description: What server software are you using? (Paper, Spigot, etc.)
      placeholder: "e.g., Paper"
    validations:
      required: true

  - type: input
    id: itemsadder-version
    attributes:
      label: ItemsAdder Version
      description: What version of ItemsAdder are you using?
      placeholder: "e.g., 4.0.0"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: ItemsAdder Furniture Protection Version
      description: What version of our plugin are you using?
      placeholder: "e.g., 1.0"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it
      placeholder: |
        1. Place furniture...
        2. Try to break it...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output
      render: shell

  - type: dropdown
    id: minigame
    attributes:
      label: Minigame Related
      description: Is this issue related to a specific minigame?
      options:
        - "No"
        - "BedWars"
        - "Other minigame"
    validations:
      required: true