name: Build Minecraft Plugin

on:
  push:
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: '**/*.md' # Checks all Markdown files in the repository
          fix: true # automatically fixes simple problems
          config: 'markdownlint.json'  # if you have a configuration file
#        continue-on-error: true  # to prevent the build from crashing due to errors in the documentation

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4  # Обновлённая версия

      - name: Build with Gradle
        run: ./gradlew build  # Вместо deprecated "arguments"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IAFurnitureBreakRestricter
          path: ${{ github.workspace }}/build/libs/